# Generated by Django 5.0.4 on 2024-04-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=100, null=True)),
                ('cantitate', models.IntegerField(default=0)),
                ('descriere', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_client', models.CharField(blank=True, max_length=100, null=True)),
                ('cantitate', models.IntegerField(default=0)),
                ('data_plasare', models.DateField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.material')),
            ],
        ),
        migrations.CreateModel(
            name='RaportCalitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_rezultat', models.CharField(blank=True, max_length=100, null=True)),
                ('data_test', models.DateField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baza.material')),
            ],
        ),
    ]
